### ISSUE TITLE
 cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by Ciclarion** [yanx27/EverybodyDanceNow_reproduce_pytorch#17]
Hello, 

I tried to use your code but i got this error message in the very first step (make_source.py). 

```
  0%|                                                 | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "make_source.py", line 80, in <module>
    paf, heatmap = get_outputs(multiplier, img, model, 'rtpose')
  File "src\PoseEstimation\evaluate\coco_eval.py", line 137, in get_outputs
    predicted_outputs, _ = model(batch_var)
  File "C:\Users\Cedric\Anaconda3\lib\site-packages\torch\nn\modules\module.py",
 line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Cedric\Anaconda3\lib\site-packages\torch\nn\parallel\data_paral
lel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\Cedric\Anaconda3\lib\site-packages\torch\nn\modules\module.py",
 line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "src\PoseEstimation\network\rtpose_vgg.py", line 161, in forward
    out1 = self.model0(x)
  File "C:\Users\Cedric\Anaconda3\lib\site-packages\torch\nn\modules\module.py",
 line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Cedric\Anaconda3\lib\site-packages\torch\nn\modules\container.p
y", line 92, in forward
    input = module(input)
  File "C:\Users\Cedric\Anaconda3\lib\site-packages\torch\nn\modules\module.py",
 line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Cedric\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", l
ine 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
```

I'm on windows 8, with cuda 10 pytorch 1.0 and cudnn v7.4.2. I tried to use pytorch 0.4.1 to see, but same error. I changed the nbThread to 0 as you precise.  

Do you have any idea ?

**Comment by seaweiqing** [comment]
Please try the method provided on [this website](https://www.jianshu.com/p/bf183355f0e7)

Hope this would be helpful for you :)

**Comment by seaweiqing** [comment]
Also, [this web](https://github.com/SeanNaren/deepspeech.pytorch/issues/32) once stated similar problem as yours, you may have a glance at it:

**Comment by Ciclarion** [comment]
Thanks for the answer. Otherwise, as i'm on Windows so i've no folder .nv to remove for the first method.

The second link supposed that the problem is with the pytorch installation, but i've already try to reinstall it from the website, without change. 

Strangely, I tried to put ` torch.backends.cudnn.benchmark = False` in the make_source.py file, but i've the same error message as before.
