### ISSUE TITLE
error in transfer.py

### ISSUE THREAD

**Issue by JustDoSomethong** [yanx27/EverybodyDanceNow_reproduce_pytorch#22]
Hi, when I use transfer.py, I reported a mistake here. 
  0%|          | 0/1000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "D:/GAN/everybody dance/pytorch/EverybodyDanceNow_reproduce_pytorch-1.0/transfer.py", line 35, in <module>
    for data in tqdm(dataset):  # <torch.utils.data.dataloader.DataLoader object at 0x0000026E4176FFD0>
  File "C:\Users\Jimi-iot\AppData\Local\Programs\Python\Python35\lib\site-packages\tqdm\_tqdm.py", line 979, in __iter__
    for obj in iterable:
  File "C:\Users\Jimi-iot\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "C:\Users\Jimi-iot\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
    w.start()
  File "C:\Users\Jimi-iot\AppData\Local\Programs\Python\Python35\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Jimi-iot\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Jimi-iot\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\Jimi-iot\AppData\Local\Programs\Python\Python35\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Jimi-iot\AppData\Local\Programs\Python\Python35\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'module'>: attribute lookup module on builtins failed

can you give me any suggestions? thx

**Comment by ManInBlackie** [comment]
+1
