### ISSUE TITLE
what if i don't do the face_enhance process,and just run make_gif.py

### ISSUE THREAD

**Issue by jackylee1** [yanx27/EverybodyDanceNow_reproduce_pytorch#29]
what if i don't do the face_enhance process,and just run make_gif.py

**Comment by jackylee1** [comment]
Animation size has reached 21099382 bytes, exceeding the limit of 20971520.0. If you're sure you want a larger animation embedded, set the animation.embed_limit rc parameter to a larger value (in MB). This and further frames will be dropped.
MovieWriter imagemagick unavailable. Trying to use pillow instead.

**Comment by jackylee1** [comment]
where is the result after make_gif.py

**Comment by jackylee1** [comment]
i experiment on google colab,and i don't know how to install imagemagick on it,how to use pillow instead

**Comment by jackylee1** [comment]
Traceback (most recent call last):
  File "./face_enhancer/prepare.py", line 7, in <module>
    face_sync_dir.mkdir(exist_ok=True)
  File "/usr/lib/python3.6/pathlib.py", line 1248, in mkdir
    self._accessor.mkdir(self, mode)
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '../data/face/ '

**Comment by fantasy-fish** [comment]
I’m totally fine with no face enhancement.
For the error you posted, there's an extra space at the end of the path '../data/face/ '. The error will disappear after you delete the extra spaces.

**Comment by jackylee1** [comment]
@fantasy-fish
 Prepare test_real....
100% 617/617 [51:38<00:00,  4.37s/it]
Prepare test_sync....
Traceback (most recent call last):
  File "prepare.py", line 43, in <module>
    import src.config.test_opt as opt
ModuleNotFoundError: No module named 'src'
i'm quite confused.that's strange

**Comment by jackylee1** [comment]
when i run ./face_hancer/prepare.py , it also show no module named data.dataloader.
and i enter face-hancer ，and run prepare.py, it shows error above.

**Comment by sandhyalaxmiK** [comment]
by adding these two following lines problem solved
import matplotlib
matplotlib.rcParams['animation.embed_limit'] = 2**128

**Comment by zlj0711** [comment]
那个no module name src的错误是怎么解决的呢

**Comment by maveeshah** [comment]
> @fantasy-fish
> Prepare test_real....
> 100% 617/617 [51:38<00:00, 4.37s/it]
> Prepare test_sync....
> Traceback (most recent call last):
> File "prepare.py", line 43, in
> import src.config.test_opt as opt
> ModuleNotFoundError: No module named 'src'
> i'm quite confused.that's strange

[https://github.com/CUHKSZ-TQL/EverybodyDanceNow_reproduce_pytorch/issues/59#issuecomment-650710466](url)

**Comment by maveeshah** [comment]
the face in the target video isn't clear enough , what more can i try, please!
