### ISSUE TITLE
pix2pixHD raise('Generator must exist!') TypeError: exceptions must derive from BaseException

### ISSUE THREAD

**Issue by benoitoutlook** [yanx27/EverybodyDanceNow_reproduce_pytorch#42]
Traceback (most recent call last):
  File "train_pose2vid.py", line 127, in <module>
    main()
  File "train_pose2vid.py", line 41, in main
    model = create_model(opt)
  File "/XXX/EverybodyDanceNow_reproduce_pytorch/src/pix2pixHD/models/models.py", line 15, in create_model
    model.initialize(opt)
  File "/XXX/EverybodyDanceNow_reproduce_pytorch/src/pix2pixHD/models/pix2pixHD_model.py", line 64, in initialize
    self.load_network(self.netG, 'G', opt.which_epoch, pretrained_path)            
  File "/XXX/EverybodyDanceNow_reproduce_pytorch/src/pix2pixHD/models/base_model.py", line 60, in load_network
    raise('Generator must exist!')
TypeError: exceptions must derive from BaseException

Any help is appreciated!

**Comment by cndxpy** [comment]
you fixed?

**Comment by chenzaiV6** [comment]
need help too

**Comment by chenzaiV6** [comment]
windows ，python3.6.5 ，anaconda

**Comment by ahhays** [comment]
Same

**Comment by karadagi** [comment]
same problem with Google Colab:(

**Comment by Aquahugs** [comment]
Im also having this problem :(

**Comment by quleileileilei** [comment]
Have anyone solved this problem? I need help too.

**Comment by uluumbch** [comment]
any solution please?
