### ISSUE TITLE
No module named openpose_utils

### ISSUE THREAD

**Issue by Tnze** [yanx27/EverybodyDanceNow_reproduce_pytorch#44]
```
Traceback (most recent call last):
  File "make_source.py", line 1, in <module>
    from openpose_utils import remove_noise, get_pose
ImportError: No module named openpose_utils
```

**Comment by Keneyr** [comment]
+1

**Comment by Keneyr** [comment]
How to solve this problem? there are lots of importXXX wrong in my files. Where is the evaluate.coco_eval, and where is the network.rtpose_vgg???

**Comment by Keneyr** [comment]
from src.utils.openpose_utils ， or it's the pycharm problem

**Comment by Tnze** [comment]
I am not using pycharm.

**Comment by sunshinewhy** [comment]
Traceback (most recent call last):
  File "EverybodyDanceNow_reproduce_pytorch-master/make_source.py", line 47, in <module>
    from evaluate.coco_eval import get_multiplier, get_outputs
ModuleNotFoundError: No module named 'evaluate'
How to solve this error?
Thank you!
