### ISSUE TITLE
Animation size has reached 20989202 bytes, exceeding the limit of 20971520.0. If you're sure you want a larger animation embedded, set the animation.embed_limit rc parameter to a larger value (in MB). This and further frames will be dropped.

### ISSUE THREAD

**Issue by Keneyr** [yanx27/EverybodyDanceNow_reproduce_pytorch#50]
Animation size has reached 20989202 bytes, exceeding the limit of 20971520.0. If you're sure you want a larger animation embedded, set the animation.embed_limit rc parameter to a larger value (in MB). This and further frames will be dropped.
Traceback (most recent call last):
  File "make_gif.py", line 60, in <module>
    js_anim = HTML(anim.to_jshtml())
  File "/home/home1/yqr/anaconda3/envs/pytorch/lib/python3.6/site-packages/matplotlib/animation.py", line 1398, in to_jshtml
    self.save(str(path), writer=writer)
  File "/home/home1/yqr/anaconda3/envs/pytorch/lib/python3.6/site-packages/matplotlib/animation.py", line 1175, in save
    anim._draw_next_frame(d, blit=False)
  File "/home/home1/yqr/anaconda3/envs/pytorch/lib/python3.6/site-packages/matplotlib/animation.py", line 1212, in _draw_next_frame
    self._draw_frame(framedata)
  File "/home/home1/yqr/anaconda3/envs/pytorch/lib/python3.6/site-packages/matplotlib/animation.py", line 1767, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
  File "make_gif.py", line 42, in animate
    target_synth = io.imread(target_synth_paths[nframe])
IndexError: list index out of range

Anybody meet the same problem?

**Comment by 8secz-johndpope** [comment]
duplicate https://github.com/CUHKSZ-TQL/EverybodyDanceNow_reproduce_pytorch/issues/29

**Comment by sandhyalaxmiK** [comment]
write following lines in make_gif.py 
import matplotlib
matplotlib.rcParams['animation.embed_limit'] = 2**128

**Comment by maveeshah** [comment]
MovieWriter imagemagick unavailable; trying to use pillow instead.
Traceback (most recent call last):
  File "make_gif.py", line 58, in <module>
    myAnimation.save("output.gif", writer="imagemagick")
  File "/home/mavee_shah/miniconda3/lib/python3.7/site-packages/matplotlib/animation.py", line 1111, in save
    extra_args=extra_args, metadata=metadata)
TypeError: 'str' object is not callable

**Comment by sxaxmz** [comment]
Hi @maveeshah , may I ask how did you overcome the issue?

**Comment by Momooou** [comment]
> write following lines in make_gif.py import matplotlib matplotlib.rcParams['animation.embed_limit'] = 2**128

According to the error message, the limit is calculated in MB. Setting it to 2**128 wouldn't be too high?

I searched for posts from different ppl who came accross this issue too. All solution suggests them to set the limit to 2**128 as well. Why is it so? Is 2**128 a special number?
