### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\x0a'.  python train_pose2vid.py 

### ISSUE THREAD

**Issue by Ai-is-light** [yanx27/EverybodyDanceNow_reproduce_pytorch#58]
when I ran python  python train_pose2vid.py under the env: Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'0.4.1'

I got the following error:

Traceback (most recent call last):
  File "train_pose2vid.py", line 130, in <module>
    main()
  File "train_pose2vid.py", line 44, in main
    model = create_model(opt)
  File "/data2/project_dancing_score/EverybodyDanceNow_reproduce_pytorch/src/pix2pixHD/models/models.py", line 15, in create_model
    model.initialize(opt)
  File "/data2//project_dancing_score/EverybodyDanceNow_reproduce_pytorch/src/pix2pixHD/models/pix2pixHD_model.py", line 83, in initialize
    self.criterionVGG = networks.VGGLoss(self.gpu_ids)
  File "/data2//project_dancing_score/EverybodyDanceNow_reproduce_pytorch/src/pix2pixHD/models/networks.py", line 118, in __init__
    self.vgg = Vgg19().cuda()
  File "/data2//project_dancing_score/EverybodyDanceNow_reproduce_pytorch/src/pix2pixHD/models/networks.py", line 392, in __init__
    vgg_pretrained_features = models.vgg19(pretrained=True).features
  File "/data//anaconda3/envs/py36t41/lib/python3.6/site-packages/torchvision/models/vgg.py", line 180, in vgg19
    model.load_state_dict(model_zoo.load_url(model_urls['vgg19']))
  File "/data//anaconda3/envs/py36t41/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 66, in load_url
    return torch.load(cached_file, map_location=map_location)
  File "/data//anaconda3/envs/py36t41/lib/python3.6/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/data/anaconda3/envs/py36t41/lib/python3.6/site-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, '\x0a'.

**Comment by Ai-is-light** [comment]
py36t41/lib/python3.6/site-packages/torch/serialization.py", line 533, in _load
 magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, '\x0a'.

while in the serialization.py
 15 if sys.version_info[0] == 2:
 16     import cPickle as pickle
 17 else:
 18     import pickle
 19     import pathlib
 20
 21 DEFAULT_PROTOCOL = 2
 22
 23 LONG_SIZE = struct.Struct('=l').size
 24 INT_SIZE = struct.Struct('=i').size
 25 SHORT_SIZE = struct.Struct('=h').size
 26
 27 MAGIC_NUMBER = 0x1950a86a20f9469cfc6c
 28 PROTOCOL_VERSION = 1001
 29 STORAGE_KEY_SEPARATOR = ',


 def save(obj, f, pickle_module=pickle, pickle_protocol=DEFAULT_PROTOCOL):
183     """Saves an object to a disk file.
184
185     See also: :ref:`recommend-saving-models`
186
187     Args:
188         obj: saved object
189         f: a file-like object (has to implement write and flush) or a string
190            containing a file name
191         pickle_module: module used for pickling metadata and objects
192         pickle_protocol: can be specified to override the default protocol
193
194     .. warning::
195         If you are using Python 2, torch.save does NOT support StringIO.StringIO
196         as a valid file-like object. This is because the write method should return
197         the number of bytes written; StringIO.write() does not do this.
198
199         Please use something like io.BytesIO instead.

531     print("---"*16)
532     print(f)
533     magic_number = pickle_module.load(f)
534     print("magic_number: ", magic_number)
------------------------------------------------
<_io.BufferedReader name='/data/home/yonasyu/.torch/models/vgg19-dcbb9e9d.pth'>
