### ISSUE TITLE
run train_pose2vid.py，it shows ModuleNotFoundError: No module named 'data.data_loader'

### ISSUE THREAD

**Issue by wangzheliu** [yanx27/EverybodyDanceNow_reproduce_pytorch#59]
(torch4) [liu@no3@node04 EverybodyDanceNow_reproduce_pytorch]$ python train_pose2vid.py
Traceback (most recent call last):
  File "train_pose2vid.py", line 17, in <module>
    from data.data_loader import CreateDataLoader
ModuleNotFoundError: No module named 'data.data_loader'
how to fix it？

**Comment by sandhyalaxmiK** [comment]
create empty __init__.py file in data folder

**Comment by disanda** [comment]
it is in main file , dir is  ‘.\src\pix2pixHD\data’ , and there are a file named 'data_loader.py' .it is what your need.do you find it?

**Comment by maveeshah** [comment]
previous code
`pix2pixhd_dir = Path('./src/pix2pixHD/')
sys.path.append(str(pix2pixhd_dir))

from data.data_loader import CreateDataLoader
from models.models import create_model
import util.util as util
from util.visualizer import Visualizer
from util import html
import src.config.test_opt as opt`


change it to
`pix2pixhd_dir = Path('./src/')
sys.path.append(str(pix2pixhd_dir))

from pix2pixHD.data.data_loader import CreateDataLoader
from pix2pixHD.models.models import create_model
import pix2pixHD.util.util as util
from pix2pixHD.util.visualizer import Visualizer
from pix2pixHD.util import html
import config.test_opt as opt`

you'll have to do it in many files and it'll work smoothly then

**Comment by maveeshah** [comment]
> (torch4) [liu@no3@node04 EverybodyDanceNow_reproduce_pytorch]$ python train_pose2vid.py
> Traceback (most recent call last):
> File "train_pose2vid.py", line 17, in
> from data.data_loader import CreateDataLoader
> ModuleNotFoundError: No module named 'data.data_loader'
> how to fix it？

previous code
`pix2pixhd_dir = Path('./src/pix2pixHD/')
sys.path.append(str(pix2pixhd_dir))

from data.data_loader import CreateDataLoader
from models.models import create_model
import util.util as util
from util.visualizer import Visualizer
from util import html
import src.config.test_opt as opt`

change it to
`pix2pixhd_dir = Path('./src/')
sys.path.append(str(pix2pixhd_dir))

from pix2pixHD.data.data_loader import CreateDataLoader
from pix2pixHD.models.models import create_model
import pix2pixHD.util.util as util
from pix2pixHD.util.visualizer import Visualizer
from pix2pixHD.util import html
import config.test_opt as opt`

you'll have to do it in many files and it'll work smoothly then
