### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by ChenChao20180801** [yanx27/EverybodyDanceNow_reproduce_pytorch#6]
Traceback (most recent call last):
  File "D:/python/files/EverybodyDanceNow_reproduce_pytorch/train_pose2vid.py", line 127, in <module>
    main()
  File "D:/python/files/EverybodyDanceNow_reproduce_pytorch/train_pose2vid.py", line 49, in main
    for i, data in enumerate(dataset, start=epoch_iter):
  File "C:\Users\chenchao\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 501, in __iter__
    return _DataLoaderIter(self)
  File "C:\Users\chenchao\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 289, in __init__
    w.start()
  File "C:\Users\chenchao\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\chenchao\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\chenchao\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\chenchao\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\chenchao\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle module objects
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\chenchao\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\chenchao\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by yanx27** [comment]
If you have not multi-GPU, choose `os.environ['CUDA_VISIBLE_DEVICES'] = "0"`

**Comment by yanx27** [comment]
If you don't have multi-GPU, try `os.environ['CUDA_VISIBLE_DEVICES'] = "0"`

**Comment by yanx27** [comment]
Sorry, I think it's multiprocessing problems in Windows,  if you don't have linux and ubuntu, you can set `nThreads=0` in `EverybodyDanceNow_reproduce_pytorch/src/config/train_opt.py`. Thanks you for you feedback :)

**Comment by ChenChao20180801** [comment]
Thank you for your timely reply. The problem has been solved
