### ISSUE TITLE
make_gif.py

### ISSUE THREAD

**Issue by ZJ9527** [yanx27/EverybodyDanceNow_reproduce_pytorch#84]
the following is my error
Traceback (most recent call last):
  File "make_gif.py", line 52, in <module>
    anim.save("output.gif", writer="imagemagick")
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/animation.py", line 1102, in save
    alt_writer = next(writers, None)
TypeError: 'MovieWriterRegistry' object is not an iterator
how can i solve it?

**Comment by andrewhani14** [comment]
Same problem , did you solve it ?

**Comment by ZJ9527** [comment]
yes
it is a version problem
you just change the code on last line 
anim.save("output.gif", writer="imagemagick")
to
anim.save("output.gif", writer="pillow")

**Comment by ZJ9527** [comment]
what is more
the output.gif will be saved in the root directory

**Comment by andrewhani14** [comment]
Thank youu , worked for me
